version: 0.2
# env:
#   parameter-store:
#     CODEARTIFACT_AUTH_TOKEN: CODEARTIFACT_AUTH_TOKEN
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
    - chmod +x ./gradlew
  # pre_build:
  #   commands:
  #     - export SONAR_TOKEN=$(cat /tmp/SONAR_TOKEN)
  build:
    commands:
      - ./gradlew sonarqube
