version: 0.2
# env:
#   parameter-store:
    # SONAR_TOKEN:   SONAR_TOKEN
    # HOST:    HOST
    # Organization: Organization
    # Project: Project
    # CODEARTIFACT_AUTH_TOKEN: CODEARTIFACT_AUTH_TOKEN
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
    - chmod +x ./gradlew
  # pre_build:
  #   commands:
  #     - export SONAR_TOKEN=$(cat /tmp/SONAR_TOKEN)
  build:
    commands:
      # - echo "Installing JDK11 as its a dependency for sonarqube code analysis"
      # - apt-get install -y openjdk-11-jdk
      # - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      # - ./gradlew build
      - ./gradlew sonarqube
